services:
  backend:
    image: "${BACKEND_IMAGE}"
    container_name: airport-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - backend.env

  frontend:
    image: "${FRONTEND_IMAGE}"
    container_name: airport-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - frontend.env
